"""Initial migration.

Revision ID: 564c8bea96f1
Revises: 
Create Date: 2025-01-24 16:22:39.903576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c8bea96f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authType', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authType')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('metadatavalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceID', sa.Integer(), nullable=False),
    sa.Column('field1', sa.String(length=100), nullable=True),
    sa.Column('field2', sa.String(length=100), nullable=True),
    sa.Column('field3', sa.String(length=100), nullable=True),
    sa.Column('field4', sa.String(length=100), nullable=True),
    sa.Column('field5', sa.String(length=100), nullable=True),
    sa.Column('field6', sa.String(length=100), nullable=True),
    sa.Column('field7', sa.String(length=100), nullable=True),
    sa.Column('field8', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadatavalues')
    op.drop_table('users')
    op.drop_table('devices')
    op.drop_table('authentications')
    # ### end Alembic commands ###
